version: '3'

services:
  backend:
    build: ./backend_docker/
    ports:
      - "8000:8001"
    

  frontend:
    build: ./frontend_docker/
    ports:
      - "3000:3000"
    environment:
      API_URL: http://localhost:8000/
    depends_on:
      - backend